### ISSUE TITLE
Dart 2.0 support

### ISSUE THREAD

**Issue by arvanus** [pinkfish/flutter_calendar#3]
Dart 2.0 support

**Comment by wallforfry** [comment]
Is a Dart 2.0 support planned ?

**Comment by pinkfish** [comment]
It already has dart 2.0 support if you look at the published package.  I
guess I shjould close this issue :)

**Comment by pinkfish** [comment]
The latest version I just publishes has dart 2.0 support.  I use dart 2.0 at home for my main project too :)
