### ISSUE TITLE
How to limit start month and end month?

### ISSUE THREAD

**Issue by arvanus** [pinkfish/flutter_calendar#9]
How can I limit the months, not to became an infinite scroll?
For example, I want to allow the user to access just 12 months before and after a given date.
Thanks!

**Comment by Eimji** [comment]
It would be great to have this option :)

**Comment by Eimji** [comment]
I'm working to add this option, will make a PR after :)

**Comment by Eimji** [comment]
Done :)

**Comment by arvanus** [comment]
Worked! Thanks! 

@Eimji, have you already experienced a problem when you swipe the calendar, and sometimes it jumps back to the month you were at? (it was happening before your fix, don't worry ;) )
